# Generated by Django 2.1.5 on 2020-08-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0029_auto_20200809_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='registration_date',
            field=models.DateField(null=True, verbose_name='Registration Date'),
        ),
    ]
